"""Sabitler - Magic numbers yok"""

# Pencere boyutları
WINDOW_WIDTH = 520
WINDOW_HEIGHT = 650

# Ekran ayarları
DEFAULT_FONT_SIZE = 32
MIN_FONT_SIZE = 14
MAX_INPUT_LENGTH = 25
DISPLAY_PADDING_X = 20
DISPLAY_PADDING_Y = 20

# Buton ayarları
BUTTON_PAD_X = 12
BUTTON_PAD_Y = 14
BUTTON_GAP = 2

# Klavye
KEYBOARD_MAX_CHARS = 25

# Bilimsel gösterim
SCIENTIFIC_THRESHOLD = 1e15
SCIENTIFIC_SMALL_THRESHOLD = 1e-12
DECIMAL_PLACES = 12